package com.atom.crm.workbench.mapper;

import com.atom.crm.workbench.bean.Activity;

import java.util.List;
import java.util.Map;

public interface ActivityMapper {


    int insertActivityByList(List<Activity> activities);

    /**
     * 根据1个以上的id查找市场活动信息
     * @param ids
     * @return 市场活动列表
     */
    List<Activity> selectActivityByIds(String[] ids);

    /**
     * 查询所有市场活动信息
     * @return
     */
    List<Activity> selectAllActivities();

    /**
     * 根据市场活动id修改指定的市场活动数据
     * @param activity
     * @return
     */
    int updateActivityById(Activity activity);

    /**
     * 根据市场活动的id查找市场活动信息
     * @param id
     * @return
     */
    Activity selectActivityById(String id);

    /**
     * 根据市场活动id组成的数组批量删除市场活动信息。
     * @param ids
     * @return
     */
    int deleteActivityByIds(String[] ids);

    /**
     * 根据条件查询市场活动的总条数
     * @param map
     * @return
     */
    int selectCountOfActivityByCondition(Map<String, Object> map);

    /**
     * 根据条件分页查询市场活动的列表
     * @param map
     * @return
     */
    List<Activity> selectActivityByConditionForPage(Map<String, Object> map);

    /**
     * 创建市场活动
     * @param activity
     * @return
     */
    int insertActivity(Activity activity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jul 21 09:20:33 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jul 21 09:20:33 CST 2022
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jul 21 09:20:33 CST 2022
     */
    Activity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jul 21 09:20:33 CST 2022
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jul 21 09:20:33 CST 2022
     */
    int updateByPrimaryKey(Activity record);
}